workflows:
  android-workflow:
    name: Android Workflow - APK Build
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      flutter: 3.19.6  # Known stable version
      java: 11
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Clean build
        script: flutter clean
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  web-workflow:
    name: Web Build (Recommended)
    instance_type: linux_x2
    max_build_duration: 30
    environment:
      flutter: 3.19.6
    scripts:
      - name: Build web app
        script: |
          flutter pub get
          flutter build web --release
    artifacts:
      - build/web/
