workflows:
  ios-workflow:
    name: iOS Workflow - Rebuild Services
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.19.0
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Clean everything
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf build
          rm -rf .dart_tool
      - name: Completely rebuild services
        script: |
          # Remove entire services directory
          rm -rf lib/services
          mkdir -p lib/services
          
          # Create database_interface.dart
          cat > lib/services/database_interface.dart << 'EOF'
          import '../models/transaction.dart' as models;
          
          abstract class DatabaseInterface {
            Future<void> insertTransaction(models.Transaction transaction);
            Future<List<models.Transaction>> getTransactions({String? filter, String? search});
            Future<Map<String, dynamic>> getReports();
          }
          EOF
          
          # Create database_web.dart
          cat > lib/services/database_web.dart << 'EOF'
          import '../models/transaction.dart' as models;
          import 'database_interface.dart';
          
          class DatabaseWeb implements DatabaseInterface {
            static final List<models.Transaction> _transactions = [];
          
            @override
            Future<void> insertTransaction(models.Transaction transaction) async {
              _transactions.add(transaction);
            }
          
            @override
            Future<List<models.Transaction>> getTransactions({String? filter, String? search}) async {
              return _transactions;
            }
          
            @override
            Future<Map<String, dynamic>> getReports() async {
              return {'totalThisMonth': 0.0, 'categories': []};
            }
          }
          EOF
          
          # Create database_mobile.dart
          cat > lib/services/database_mobile.dart << 'EOF'
          import '../models/transaction.dart' as models;
          import 'database_interface.dart';
          
          class DatabaseMobile implements DatabaseInterface {
            static final List<models.Transaction> _transactions = [];
          
            @override
            Future<void> insertTransaction(models.Transaction transaction) async {
              _transactions.add(transaction);
            }
          
            @override
            Future<List<models.Transaction>> getTransactions({String? filter, String? search}) async {
              return _transactions;
            }
          
            @override
            Future<Map<String, dynamic>> getReports() async {
              return {'totalThisMonth': 0.0, 'categories': []};
            }
          }
          EOF
          
          # Create database_service.dart
          cat > lib/services/database_service.dart << 'EOF'
          import '../models/transaction.dart' as models;
          import '../utils/platform_helper.dart';
          import 'database_interface.dart';
          import 'database_web.dart';
          import 'database_mobile.dart';
          
          class DatabaseService {
            static DatabaseInterface? _instance;
          
            static DatabaseInterface get _database {
              if (_instance != null) return _instance!;
              
              if (PlatformHelper.isWeb) {
                _instance = DatabaseWeb();
              } else {
                _instance = DatabaseMobile();
              }
              
              return _instance!;
            }
          
            static Future<void> insertTransaction(models.Transaction transaction) async {
              await _database.insertTransaction(transaction);
            }
          
            static Future<List<models.Transaction>> getTransactions({
              String? filter,
              String? search,
            }) async {
              return await _database.getTransactions(filter: filter, search: search);
            }
          
            static Future<Map<String, dynamic>> getReports() async {
              return await _database.getReports();
            }
          }
          EOF
          
          # Create export_service.dart
          cat > lib/services/export_service.dart << 'EOF'
          import '../models/transaction.dart';
          
          class ExportService {
            static Future<String?> exportToCsv(List<Transaction> transactions) async {
              return 'Export not available in minimal version';
            }
          
            static Future<String?> exportToPdf(List<Transaction> transactions, Map<String, dynamic> reports) async {
              return 'Export not available in minimal version';
            }
          }
          EOF
          
          # Create storage_service.dart
          cat > lib/services/storage_service.dart << 'EOF'
          class StorageService {
            static String? _userNetwork;
            static bool _isFirstLaunch = true;
          
            static Future<String?> getUserNetwork() async => _userNetwork;
            static Future<void> saveUserNetwork(String network) async {
              _userNetwork = network;
              _isFirstLaunch = false;
            }
            static Future<bool> isFirstLaunch() async => _isFirstLaunch;
            static Future<void> clearUserData() async {
              _userNetwork = null;
              _isFirstLaunch = true;
            }
          }
          EOF
          
          # Remove URL launcher from screens
          find lib/screens -name "*.dart" -exec sed -i '' '/url_launcher/d' {} \;
          find lib/screens -name "*.dart" -exec sed -i '' '/launchUrl/d' {} \;
          find lib/screens -name "*.dart" -exec sed -i '' '/canLaunchUrl/d' {} \;
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/PayNote.app
          zip -r PayNote.ipa Payload
    artifacts:
      - PayNote.ipa
