workflows:
  ios-workflow:
    name: iOS Workflow for SideStore
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.19.0  # Latest stable
      xcode: 15.2      # More compatible
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build iOS app with compatibility
        script: |
          flutter build ios --release --no-codesign \
            --target-platform ios-arm64 \
            --dart-define=FLUTTER_WEB_USE_SKIA=true
      - name: Create proper IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/PayNote.app
          zip -r PayNote.ipa Payload
    artifacts:
      - PayNote.ipa
