workflows:
  ios-workflow:
    name: iOS Workflow - Minimal Dependencies
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.19.0
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Clean everything
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf build
      - name: Create minimal pubspec
        script: |
          cat > pubspec.yaml << 'EOF'
          name: paynote
          description: "PayNote - Smart USSD helper and transaction tracker"
          publish_to: 'none'
          
          version: 1.0.0+1
          
          environment:
            sdk: '>=3.2.3 <4.0.0'
          
          dependencies:
            flutter:
              sdk: flutter
            cupertino_icons: ^1.0.2
            flutter_riverpod: ^2.4.9
            path: ^1.8.3
            fl_chart: ^0.65.0
          
          dev_dependencies:
            flutter_test:
              sdk: flutter
            flutter_lints: ^2.0.0
          
          flutter:
            uses-material-design: true
          EOF
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/PayNote.app
          zip -r PayNote.ipa Payload
    artifacts:
      - PayNote.ipa
