workflows:
  ios-workflow:
    name: iOS Workflow - Fix Imports
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: 3.19.0
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Clean everything
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf build
      - name: Fix all imports and create stubs
        script: |
          # Replace export_service.dart completely
          cat > lib/services/export_service.dart << 'EOF'
          import '../models/transaction.dart';
          
          class ExportService {
            static Future<String?> exportToCsv(List<Transaction> transactions) async {
              return 'Export not available in minimal version';
            }
          
            static Future<String?> exportToPdf(List<Transaction> transactions, Map<String, dynamic> reports) async {
              return 'Export not available in minimal version';
            }
          }
          EOF
          
          # Replace database_mobile.dart completely
          cat > lib/services/database_mobile.dart << 'EOF'
          import '../models/transaction.dart' as models;
          import 'database_interface.dart';
          
          class DatabaseMobile implements DatabaseInterface {
            static final List<models.Transaction> _transactions = [];
          
            @override
            Future<void> insertTransaction(models.Transaction transaction) async {
              _transactions.add(transaction);
            }
          
            @override
            Future<List<models.Transaction>> getTransactions({String? filter, String? search}) async {
              return _transactions;
            }
          
            @override
            Future<Map<String, dynamic>> getReports() async {
              return {'totalThisMonth': 0.0, 'categories': []};
            }
          }
          EOF
          
          # Replace storage_service.dart completely
          cat > lib/services/storage_service.dart << 'EOF'
          class StorageService {
            static String? _userNetwork;
            static bool _isFirstLaunch = true;
          
            static Future<String?> getUserNetwork() async => _userNetwork;
            static Future<void> saveUserNetwork(String network) async {
              _userNetwork = network;
              _isFirstLaunch = false;
            }
            static Future<bool> isFirstLaunch() async => _isFirstLaunch;
            static Future<void> clearUserData() async {
              _userNetwork = null;
              _isFirstLaunch = true;
            }
          }
          EOF
          
          # Remove url_launcher imports and calls from all files
          find lib -name "*.dart" -exec sed -i '' '/import.*url_launcher/d' {} \;
          find lib -name "*.dart" -exec sed -i '' '/launchUrl/d' {} \;
          find lib -name "*.dart" -exec sed -i '' '/canLaunchUrl/d' {} \;
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/PayNote.app
          zip -r PayNote.ipa Payload
    artifacts:
      - PayNote.ipa
