workflows:
  ios-workflow:
    name: iOS Workflow for AltStore
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build iOS app (unsigned)
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA for AltStore
        script: |
          mkdir -p build/ios/ipa
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/
          cd build/ios/ipa
          zip -r PayNote.ipa Runner.app
    artifacts:
      - build/ios/ipa/PayNote.ipa
    publishing:
      email:
        recipients:
          - cyotero26@gmail.com
        notify:
          success: true
